<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="7.3.2" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
  <Reference Include="RockwellAutomation.FactoryTalkLogixEcho.Api.Client">
    <HintPath>C:\nuget-extracted\echo\lib\net8.0-windows7.0\RockwellAutomation.FactoryTalkLogixEcho.Api.Client.dll</HintPath>
  </Reference>

  <Reference Include="RockwellAutomation.FactoryTalkLogixEcho.Api.Interfaces">
    <HintPath>C:\nuget-extracted\echo\lib\net8.0-windows7.0\RockwellAutomation.FactoryTalkLogixEcho.Api.Interfaces.dll</HintPath>
  </Reference>
</ItemGroup>

</Project>